### ISSUE TITLE
response body of DELETE profile doesn't return the profile info

### ISSUE THREAD

**Issue by ethyl2** [Lambda-School-Labs/labs-api-starter#10]
https://github.com/Lambda-School-Labs/labs-api-starter/blob/0b14cc48214b503c04832a98dda77800d213da80/api/profile/profileRouter.js#L284

Not a big deal, but I believe that when a delete happens, the number of rows affected is returned, not the row itself:

From http://knexjs.org/#Builder-del%20/%20delete 

del / delete — .del()
Aliased to del as delete is a reserved word in JavaScript, this method deletes one or more rows, based on other conditions specified in the query. Resolves the promise / fulfills the callback with the number of affected rows for the query.

The current setup for the DELETE route returns a property of profile with its value being what is returned. The swagger docs show that a profile is expected.
*                profile:
*                  $ref: '#/components/schemas/Profile'

However, a 1 would be the expected response upon a successful deletion.

**Comment by tinomen** [comment]
Great catch. lets get that fixed
