### ISSUE TITLE
Add 'run' to instruction in README for using nodemon

### ISSUE THREAD

**Issue by ethyl2** [Lambda-School-Labs/labs-api-starter#5]
The current line about nodemon in the README is:
run: npm watch:dev to start nodemon in local dev enviornment.

When we used it, it was not successful at starting the local server.
However, 

npm run watch:dev 

was successful at starting the local server.
We suggest adding 'run' to that line of instructions.

**Comment by tinomen** [comment]
Fixed by commit [74bcc67e](https://github.com/Lambda-School-Labs/labs-api-starter/commit/4e0d60570f54cc688ffaf863fd0da00174bcc67e)
